theme: jekyll-theme-minimal
title: Print-It
description: A KDE Plasma Dolphin Service Menu
logo: https://raw.githubusercontent.com/c-hartmann/print-it/main/assets/images/print-it-logo.png
show_downloads: true
